---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="alpine" tag="latest"
    - image="alpine" tag="edge"
    - image="amazonlinux" tag="1"
    - image="centos" tag="7"
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="debian" tag="bullseye"
    - image="fedora" tag="31"
    - image="fedora" tag="latest"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"
    - image="ubuntu" tag="xenial"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "VMmBMofD/oUt+bfO7F8Z1irXjDF3WTw9xY4NCyngOJq7jk5RXmuOTXuScxaBbnGfHZNLLqgXuACSnj7GEozau4tPd966MQfmRPczAcCp+uIV/Lr5HmQJxyreAAQ3sev1FcGECjll265ROumTcsCzOgwKRB3k675F6UOxE2v7oQo0reTkfyLp+nvOjhzP8IHZlDgsqGMQP2qIrPjIaNgJR6+GsudR/XDmmqUbIXj5v+cZ6JTx/ZkTf4T+tp15VudvcZlZN6ysCkOJ+c1MKZ5+ehyVYiPoAxsqHxXdqStOsB4z0wsprFAe/vIhd6tItFSdnKe9dOh+YxAG2mN+Kb/9Vg/FHuBy2Z68z4ViQhyEKMMG4tNugjXZzkA/nrL27QCNOVPIPwEwoArpq5/lZ9sm5HAHkS5KE7E8xiVpDbFM9yFsgEIxtXIOAioP2Z1pczTocdbfJ9/XAHi88RPh3Z2TwwIR3xNlJlUj054hpjjNiczOxoCyY0AFR+QtIAUE8l9pAJ1XAF7hqU40VhDLHQoiRdaTTodRqg8aWdQX3jdh4+EFohuNevakhr1cosUSnO6MffepM30rf6uVHPxy1pqgpUr8F/fyq1UwtXVN3vxwbASOzKLiO6WORphyAeAt9hnQ/YmLHSGGSfu3uohyiUxFMVyYNWGZ+S9k4KhHdCSpMY4="
  email: false
