---
# tasks file for sudo-pair
- name: include assert.yml
  include_tasks: assert.yml

- name: install requirements for cargo
  package:
    name: "{{ cargo_requirements }}"
    state: present

- name: download installer rustup
  get_url:
    url: https://static.rust-lang.org/rustup.sh
    dest: "{{ cargo_tmp }}/rustup.sh"
    mode: "750"
    validate_certs: no

- name: run installer rustup
  command: ./rustup.sh -y
  args:
    chdir: "{{ cargo_tmp }}"
    creates: "{{ cargo_prefix }}/bin/cargo"
  environment:
    CARGO_HOME: "{{ cargo_prefix }}"
    TMPDIR: "{{ cargo_tmp }}"
