---
# tasks file for sudo-pair
- name: install requirements for cargo
  package:
    name: "{{ cargo_requirements }}"
    state: "{{ cargo_package_state }}"

- name: download installer rustup
  get_url:
    url: https://static.rust-lang.org/rustup.sh
    dest: /tmp/rustup.sh
    mode: 0750
    validate_certs: no

- name: run installer rustup
  command: ./rustup.sh
  args:
    chdir: /tmp
    creates: /usr/local/bin/cargo
